[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
cache_path  = 'forge-cache'
gas_reports = ["*"]
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 1_000
evm_version = 'cancun'

[fuzz]
runs = 10_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
